# Generated by Django 3.0.4 on 2020-03-27 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20200326_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crawler.CarBrand'),
        ),
        migrations.AlterField(
            model_name='carmodeldetail',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crawler.CarModel'),
        ),
    ]
