# Generated by Django 3.0.4 on 2020-03-27 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20200327_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(db_column='brand', on_delete=django.db.models.deletion.PROTECT, to='crawler.CarBrand'),
        ),
    ]
