# Generated by Django 3.0.4 on 2020-03-27 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_auto_20200327_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodeldetail',
            name='model',
            field=models.ForeignKey(db_column='model', on_delete=django.db.models.deletion.PROTECT, to='crawler.CarModel'),
        ),
    ]
