# Generated by Django 3.0.4 on 2020-03-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_auto_20200327_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='carid',
            new_name='carId',
        ),
        migrations.AddField(
            model_name='carinfo',
            name='catg_modeldetail_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='price',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
