# Generated by Django 3.0.4 on 2020-03-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_auto_20200331_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='info',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
