# Generated by Django 3.0.4 on 2020-04-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_auto_20200331_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarGrade',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('modelDetail', models.ForeignKey(db_column='model', on_delete=django.db.models.deletion.PROTECT, to='crawler.CarModel')),
            ],
            options={
                'db_table': 'car_category_model_detail_grade',
            },
        ),
    ]
