# Generated by Django 3.0.4 on 2020-04-27 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_cargrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargrade',
            name='modelDetail',
            field=models.ForeignKey(db_column='model', on_delete=django.db.models.deletion.PROTECT, to='crawler.CarModelDetail'),
        ),
    ]
