# Generated by Django 3.0.4 on 2020-04-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0013_auto_20200428_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='catg_grade_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='catg_modeldetail_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
