# Generated by Django 3.0.4 on 2020-05-15 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0014_auto_20200428_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarGradeSubGroup',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('grade', models.ForeignKey(db_column='grade', on_delete=django.db.models.deletion.PROTECT, to='crawler.CarGrade')),
            ],
            options={
                'db_table': 'car_category_model_detail_grade_subgroup',
            },
        ),
    ]
