# Generated by Django 3.0.4 on 2020-05-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0015_cargradesubgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarGradeSub',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('gradeSubGroup', models.ForeignKey(db_column='gradeSubGroup', on_delete=django.db.models.deletion.PROTECT, to='crawler.CarGradeSubGroup')),
            ],
            options={
                'db_table': 'car_category_model_detail_grade_sub',
            },
        ),
    ]
