# Generated by Django 3.0.4 on 2020-05-21 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0017_auto_20200521_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargradesub',
            name='gradeSubGroup',
            field=models.ForeignKey(db_column='gradeSubGroup', on_delete=django.db.models.deletion.PROTECT, related_name='cargradesubs', to='crawler.CarGradeSubGroup'),
        ),
    ]
