# Generated by Django 3.0.4 on 2020-05-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0018_auto_20200521_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='catg_brand_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='catg_grade_sub_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='catg_grade_subgroup_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='catg_model_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='distance',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='init_regdate_month',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='init_regdate_year',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='model_year',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='regdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
