# Generated by Django 3.0.4 on 2020-05-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0019_auto_20200522_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='catg_grade_sub_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='catg_grade_subgroup_id',
            field=models.IntegerField(default=None),
        ),
    ]
