# Generated by Django 3.0.4 on 2020-05-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0020_auto_20200522_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='region',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
