# Generated by Django 3.0.4 on 2020-09-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0021_carbrand_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='scrap',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='scrap',
            field=models.IntegerField(default=None),
        ),
    ]
