# Generated by Django 3.0.4 on 2020-09-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0022_auto_20200918_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrand',
            name='scrap',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='scrap',
        ),
        migrations.AlterModelTable(
            name='carinfo',
            table='web_scraped_car_info_temp',
        ),
    ]
