# Generated by Django 3.0.4 on 2020-09-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0023_auto_20200918_1728'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carinfo',
            table='web_scraped_car_info',
        ),
    ]
