# Generated by Django 3.0.4 on 2020-09-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0025_auto_20200924_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargrade',
            name='checked',
            field=models.IntegerField(default=None),
        ),
    ]
