# Generated by Django 3.0.4 on 2020-10-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0026_cargrade_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinfo',
            name='model_year',
        ),
    ]
