# Generated by Django 3.0.4 on 2020-10-19 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0027_remove_carinfo_model_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='regdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
